[package]
name = "hello-printer"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"
resolver = "2"

[dependencies]
sel-claw = { path = "/home/chunky/Devel/sel-claw" }
ferros = { path = "../../.." }
