### Sabre (ARMv7 imx6)
[build.sabre]
cross_compiler_prefix = "arm-linux-gnueabihf-"

[build.sabre.debug]
make_root_task = "./cargo-build.sh --target=armv7-unknown-linux-gnueabihf -vv"
root_task_image = "target/armv7-unknown-linux-gnueabihf/debug/root-task"

[build.sabre.release]
make_root_task = "./cargo-build.sh --target=armv7-unknown-linux-gnueabihf --release"
root_task_image = "target/armv7-unknown-linux-gnueabihf/release/root-task"

### virt (ARMv8)
[build.virt]
cross_compiler_prefix = "aarch64-linux-gnu-"

[build.virt.debug]
make_root_task = "./cargo-build.sh --target=aarch64-unknown-linux-gnu -vv"
root_task_image = "target/aarch64-unknown-linux-gnu/debug/root-task"

[build.virt.release]
make_root_task = "./cargo-build.sh --target=aarch64-unknown-linux-gnu --release -vv"
root_task_image = "target/aarch64-unknown-linux-gnu/release/root-task"

[sel4]
kernel = { git = "https://github.com/seL4/sel4.git", branch = "master" }
tools = { git = "https://github.com/seL4/sel4_tools.git", branch = "master" }
util_libs = { git = "https://github.com/seL4/util_libs.git", branch = "master" }
musl_libc = { git = "https://github.com/seL4/musllibc.git", branch = "sel4" }

### arch

[sel4.config.arm]
KernelArch = 'arm'
KernelArchArm = true
KernelIPCBufferLocation = 'threadID_register'

### sel4_arch

[sel4.config.aarch32]
KernelSel4Arch = 'aarch32'
KernelWordSize = 32

[sel4.config.aarch64]
KernelSel4Arch = 'aarch64'
KernelWordSize = 64

### platform

[sel4.config.sabre]
KernelPlatform = "imx6"
KernelPlatformSabre = true
KernelHaveFPU = true
KernelSel4ArchArmHyp = false

[sel4.config.virt]
KernelPlatform = 'virt'
KernelHaveFPU = true
ElfloaderImage = 'elf'
KernelSel4ArchArmHyp = true

### Build mode

[sel4.config.debug]
KernelPrinting = true
KernelDebugBuild = true

[sel4.config.release]
KernelPrinting = true
KernelDebugBuild = false
KernelOptimisation = '-O2'

[sel4.config]
KernelColourPrinting = true
KernelUserStackTraceLength = 16
KernelVerificationBuild = false
KernelBenchmarks = 'none'
KernelFastpath = true
LibSel4FunctionAttributes = 'public'
KernelNumDomains = 1
HardwareDebugAPI = false
KernelFWholeProgram = false
KernelResetChunkBits = 8
KernelNumPriorities = 256
KernelStackBits = 12
KernelTimeSlice = 5
KernelTimerTickMS = 2
KernelMaxNumNodes = 1
KernelRetypeFanOutLimit = 16384
KernelRootCNodeSizeBits = 19
KernelMaxNumBootinfoUntypedCaps = 230
KernelSupportPCID = false
KernelDebugDisablePrefetchers = false
KernelExportPMCUser = false
KernelFPU = 'FXSAVE'
KernelFPUMaxRestoresSinceSwitch = 64
KernelFSGSBase = 'msr'
KernelHugePage = true
KernelIOMMU = false
KernelIRQController = 'IOAPIC'
KernelIRQReporting = true
KernelLAPICMode = 'XAPIC'
KernelMaxNumIOAPIC = 1
KernelMaxNumWorkUnitsPerPreemption = 100
KernelMultiboot1Header = true
KernelMultiboot2Header = true
KernelMultibootGFXMode = 'none'
KernelSkimWindow = true
KernelSyscall = 'syscall'
KernelXSaveSize = 576
LinkPageSize = 4096

[metadata]
root_task_stack_bytes = 2097152

